import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { yekan } from "./fonts/YekanBakh/yekan";
import { AppSidebar } from "@/components/app-sidebar";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "Bicycle Gloves Gold - Cycle Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={`${yekan.variable} ${yekan.className}`}>
        <Providers>
          <AppSidebar />
          <main>
            <Navbar />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
